# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

pod 'HandyJSON', '~> 1.7.2'
target 'Model-Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Model-Swift

end
